### PR TITLE
Tokendevel

### PR DESCRIPTION
**Pull request by adamdriscoll**
The tests were relying on each other to start flancy. I changed it to call New-Flancy in the tests and clean up in an AfterEach block. Seems to work without admin. Can you try on your box to make sure that fixes it?

### CODE REVIEW

**Comment by toenuff** [comment]
The example is broken if you uncomment the auth stuff.  It now lets you create the /authenticate endpoint and that works, but when you use the token you get 401

**Comment by toenuff** [comment]
Just checked with latest change - still no good - goal is to put the example.ps1 stuff into the test, but if you get the example working, I'll finish up the tests.

**Comment by adamdriscoll** [comment]
Yeah that's weird. Looking...

**Comment by adamdriscoll** [comment]
IDK why but I can't see which lines you are commenting on.

**Comment by adamdriscoll** [comment]
Nevermind...

**Comment by toenuff** [comment]
Click the hash, it will bring you to the file and you'll see it inline

**Comment by adamdriscoll** [comment]
Wow. Maybe I should close this pull request.

**Pull request closed without merging**
